version: '3.8'
services:
  app:
    build: .
    container_name: my-python-app
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    command: ["python", "Bucket.py"]
