version: '3.8'
 
services:
  app:
    build: .
    container_name: my-python-app
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID=AKIATCKAR64NNEMN6FXD
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=ap-south-1
    command: ["python", "Bucket.py"]
